[supabase]
url = "https://hvxbukbuaqpdmcylfiif.supabase.co"
key = "sb_publishable_Nr4QVVXPIv1y0gQ1s5muFA_KXMWbPu3"

[postgres]
host = "aws-1-eu-west-1.pooler.supabase.com"
database = "postgres"
user = "postgres.hvxbukbuaqpdmcylfiif"
password = "KianGym2026Secure"
port = 5432